### ISSUE TITLE
auto-comment stop working

### ISSUE THREAD

**Issue by fgl27** [boyney123/auto-comment#7]
It was working just fine as you can see here
https://github.com/fgl27/smarttv-twitch/issues/4

but it stop after some time, I notice it stooped working for me in last February (see my issue 5 bellow first I notice).

I uninstall and reinstall from
https://github.com/apps/auto-comment

auto-comment.yml file was not changed

but no auto comment see here:
https://github.com/fgl27/smarttv-twitch/issues/5
https://github.com/fgl27/smarttv-twitch/issues/6
https://github.com/fgl27/smarttv-twitch/issues/7

Can you help @boyney123 ?

**Comment by fgl27** [comment]
Maybe is a conflict with a organization, I wasn't part of one before, and I notice the issue after I enter one.

git setting seems fine

![Screenshot from 2019-04-12 12-35-13](https://user-images.githubusercontent.com/13755892/56049293-89df6880-5d1f-11e9-8644-027f3e4ae566.png)

**Comment by fgl27** [comment]
OK
https://github.com/fgl27/smarttv-twitch/commit/d3dd44a17389e3c0179be3440ae53e803ffd1b45

**Comment by boyney123** [comment]
Hey @fgl27 

Seems like you fixed the issue 👍. Sorry for taking a while to get back to you.
